[package]
name = "file_transfer_client"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

pnet = "0.31.0"
pnet_datalink = "0.31.0"